# Generated by Django 4.0.4 on 2022-08-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_codregistro_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codregistro',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
