# Generated by Django 4.0.4 on 2022-08-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_codregistro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='codregistro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
